version: '2'
services:
    web:
        build: ./nginx
        volumes:
            - .:/usr/share/nginx/html/public
        links:
            - php
        ports:
            - "${DOCKER_NGINX_PORT}:80"
    php:
        build: ./php
        volumes:
            - .:/usr/share/nginx/html/public
        links:
            - db
        expose:
            - "9000"
    db:
        image: mysql:latest
        restart: always
        ports:
            - "${DB_PORT}:3306"
        environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
